version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:4000

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - SQL_SERVER_HOST=mssql
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_USER=your_user
      - SQL_SERVER_PASSWORD=your_password
      - SQL_SERVER_DATABASE=your_database
      - MONGODB_URI=mongodb://mongo:27017/chatlogs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_API_KEY=your_ai_api_key

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=your_password
    ports:
      - "1433:1433"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge